<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Version>1.1.0</Version>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <EnableHarmony>true</EnableHarmony>
    <ModFolderName>QuickSaveLoadMenu</ModFolderName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>
</Project>
