<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AutoEatEideeBridge</AssemblyName>
    <RootNamespace>AutoEatEideeBridge</RootNamespace>
    <Version>1.5.0</Version>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
    <EnableHarmony>true</EnableHarmony>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GamePath)' == '' AND '$(SDV_GAME_DIR)' != ''">
    <GamePath>$(SDV_GAME_DIR)</GamePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
  </ItemGroup>
</Project>
